spring.application.name=GestionDuRestaurant_SpringBoot
spring.datasource.url=jdbc:postgresql://localhost:5433/RestourentManagment
spring.datasource.username=wip
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver
# Creates/updates tables
spring.jpa.hibernate.ddl-auto=update

# Show SQL for debugging
spring.jpa.show-sql=true
#my-secret-key-1234567890-abcd-*/
jwt.secret=bXktc2VjcmV0LWtleS0xMjM0NTY3ODkwLWFiY2QtKi8=
jwt.expiration=86400000